import React from "react";

function Documentation(){
    return(
    <div>
    <h1>Documentation Page</h1>
    <h2>Site Use Directions:</h2>
    <p>This site is intented for the use by  reforestation (tree planting) contractors to compile biling information on a block (worksite) basis and submit an invoice for their client to receive and pay</p>
    <h3>Home Portal</h3>
    <p>The home landing page of the web application presents the user with an option to access the Client or Contractor Portals. The Contractor portal is intended for the drafting and submission of invoices. The Client portal is intended for the client to access submitted invoices.</p>
    <h3>Contractor Home</h3>
    <p>Under heading "Start a New Invoice, the user is first presented with a form to input a set of information requirements to draft a new Invoice. Upon clicking on Draft invoice, the form input is compiled and passed to the invoice list below.</p>
    <h3>Current Invoices</h3>
    <p>The current invoice secetion presents the user with a list of current invoices. Each invoice is identified by the blockname "worksite".</p>
    <ul>
        <li>Tree Rate. Represents to contractual rate per tree for the specific cut block that the client is to pay the contractor upon successful work completion</li>
        <li>Total Planted. Represents the total amount of trees planted on a particular site</li>
        <li>Amount Due in CAD. Represents the total number of trees planted multiplied by the tree rate (rate input *.10)</li>
        <li>Current Bitcoin Rate. This shows the spot price of bitcoin generated by Coinbase's API.</li>
        <li>Current ETH Rate. This shows the spot price of ether generated by Coinbase's API.</li>
        <li>Time of price quotes. This shows the time stamp received from coinbase API to verify time of quote.</li>
        
  </ul>
  <h4>Current Invoice funtcionality defined by button</h4>
        <li>Submit Invoice. By clicking this, the invoice is marked as submitted. It can will then be sorted and appear when selected "Show submitted Invoices"</li>
        <li>Edit Invoice. By clicking this, the user is presented with an option to edit the invoice name or the total planted</li>
        <li>Mark as paid and remove. By clicking this, the invoice is deleted from the form</li>
    <h4>Sort Bar</h4>
    <ul>
        <li> Show all invoices. clicking this shows all the invioces to the user</li>
        <li>Show active invoices. Clicking this sorts the invoices so that the UI only shows active invoices</li>
        <li>Show submitted Invoices. Clicking this sorts the invoices for only those selected for submit. </li>
        <li>Clear all invoices. Deletes all the invoices regardless of active or submitted.</li>
    </ul>
    <h3>Sources</h3>
    <ul>
        <li>Coinbase</li>
        <li>Class Assignment Todo app for sorting and filtering methods</li>
        <li>Assignment 6 for data fetching methods</li>
    </ul>

    </div>
    );
}

export default Documentation;